# GitHub 标签配置

# 优先级标签
- name: "p0"
  color: "d73a4a"
  description: "必须先做（启动阶段）"
- name: "p1"
  color: "fbca04"
  description: "重要但不紧急（1-2个月内）"
- name: "p2"
  color: "008672"
  description: "探索性任务（可以延后）"

# 状态标签
- name: "待领"
  color: "7057ff"
  description: "没人做"
- name: "进行中"
  color: "0e8a16"
  description: "有人正在做"
- name: "已完成"
  color: "e1e1e1"
  description: "已完成"

# 技能标签
- name: "文案"
  color: "bfd4f2"
  description: "文案、写作"
- name: "视频"
  color: "bfd4f2"
  description: "视频制作、剪辑"
- name: "设计"
  color: "bfd4f2"
  description: "UI/UX、平面设计"
- name: "技术"
  color: "bfd4f2"
  description: "编程、开发"
- name: "运营"
  color: "bfd4f2"
  description: "社群运营、用户增长"
- name: "沟通"
  color: "bfd4f2"
  description: "沟通、社交"
- name: "社交"
  color: "bfd4f2"
  description: "社交、人脉"

# 申请流程标签
- name: "申请加入"
  color: "c5def5"
  description: "新成员申请加入"
- name: "approved"
  color: "0e8a16"
  description: "申请已通过审核"
- name: "添加资源"
  color: "c5def5"
  description: "申请添加新资源"
